%% This script defines maps that map different variables to filenames and indices


FixedParameterSets = {'lowdeathrate','highdeathrate'};

StateVariableMap1D = struct('R',1, ...
    'S',2, ...
    'E',3, ...
    'I',5, ...
    'L',7, ...
    'V',9);

StateVariableMap2D = struct('R',1, ...
    'S',2, ...
    'Ea',3, ...
    'Eb',4, ...
    'Ia',5, ...
    'Ib',6, ...
    'La',7, ...
    'Lb',8, ...
    'Va',9, ...
    'Vb',10);

StateVariables1D = {'R','S','E','I','L','V'};

StateVariables2D = {'R','S','Ea','Eb','Ia','Ib','La','Lb','Va','Vb'};
